datadump.location: 
  author: D:\astradb\libreria-astradb\libreria\src\main\resources\datos\test-authors.txt  
  works: D:\astradb\libreria-astradb\libreria\src\main\resources\datos\test-works.txt

spring:
  main:
    allow-circular-references: true
  data:
    cassandra:
        keyspace-name: main 
        username: MJMaBExFupXpsvUUSNKSYaMH
        password: 3h,-iaeAO+OUT5Mo8-r34rCZ.v5i5F+Dvj2XUs6Na+4tihXT,d,oT2yhXB55C7WOQT+,6Ukmw7s+1WqkCHW0_UXj,8f5_5_87q2M7egSArv6XFPNju4mpAJrzALu3FAn
        schema-action: recreate
        request:
            timeout: 10s
        connection:
            connect-timeout: 10s
            init-query-timeout: 10s


datastax.astra:
    secure-connect-bundle: secure-connect-libros.zip
    
astra.db:
    id: e76f338b-25ee-4c3a-ae95-15e142ec14ea-1
    region: us-east1
    keyspace: main
    application.token: AstraCS:MJMaBExFupXpsvUUSNKSYaMH:53df10cb61742863348ee8f0a4e9e86105cf9a2868982ff87a85bb064b67899f


